/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BL.Konto;
import Benutzer.KontoBenutzer;
import java.util.LinkedList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author David
 */
public class KontoGUI extends javax.swing.JFrame {

    /**
     * Creates new form KontoGUI
     */
    LinkedList<Thread> users = new LinkedList<Thread>();
    Konto konto = new Konto();
    DefaultListModel dlm = new DefaultListModel();
    public KontoGUI() {
        initComponents();
        liUser.setModel(dlm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupUser = new javax.swing.JPopupMenu();
        miAddUser = new javax.swing.JMenuItem();
        miTestPerformance = new javax.swing.JMenuItem();
        panelAccount = new javax.swing.JPanel();
        lbAmount = new javax.swing.JLabel();
        panelUser = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        liUser = new javax.swing.JList<>();
        panelOutput = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taOutput = new javax.swing.JTextArea();

        miAddUser.setText("Add user");
        miAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAddUserActionPerformed(evt);
            }
        });
        popupUser.add(miAddUser);

        miTestPerformance.setText("Perform account test");
        popupUser.add(miTestPerformance);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelAccount.setBorder(javax.swing.BorderFactory.createTitledBorder("Account"));
        panelAccount.setLayout(new java.awt.BorderLayout());
        panelAccount.add(lbAmount, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(panelAccount, java.awt.BorderLayout.PAGE_END);

        panelUser.setBorder(javax.swing.BorderFactory.createTitledBorder("User"));
        panelUser.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setComponentPopupMenu(popupUser);

        liUser.setComponentPopupMenu(popupUser);
        jScrollPane1.setViewportView(liUser);

        panelUser.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelUser, java.awt.BorderLayout.LINE_START);

        panelOutput.setBorder(javax.swing.BorderFactory.createTitledBorder("Log-output"));
        panelOutput.setLayout(new java.awt.BorderLayout());

        taOutput.setColumns(20);
        taOutput.setRows(5);
        jScrollPane2.setViewportView(taOutput);

        panelOutput.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelOutput, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAddUserActionPerformed
        String in = JOptionPane.showInputDialog("Please enter the name: ");
        KontoBenutzer user = new KontoBenutzer(konto);
        users.add(new Thread(user,in));
        dlm.addElement(in);
    }//GEN-LAST:event_miAddUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KontoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KontoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KontoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KontoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KontoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbAmount;
    private javax.swing.JList<Thread> liUser;
    private javax.swing.JMenuItem miAddUser;
    private javax.swing.JMenuItem miTestPerformance;
    private javax.swing.JPanel panelAccount;
    private javax.swing.JPanel panelOutput;
    private javax.swing.JPanel panelUser;
    private javax.swing.JPopupMenu popupUser;
    private javax.swing.JTextArea taOutput;
    // End of variables declaration//GEN-END:variables
}
